### PR TITLE
Added compatibility to MANY mods using hte "official" forge and fabric tags.

### PR DESCRIPTION
**Pull request by BugInYourCode01**
Finally the pull request is out.
Each tag "createdeco:internal/..." was rewritten to "forge:..." for forge or "c..." for fabric. These are the official Fabric tags, at least that's how they appear in Fabric API! Additionally, Create, Create: Crafts Additions, Create: Dreams and Desires and many other mods are based on it.
I also converted all (I think) item ingredients in the recipes into tags.

I would recommend that you split the Github branch 1.20.1--main into 1.20.1-forge and 1.20.1-fabric, as a lot of the recipes differ from forge to fabric. If the branches split, I would be happy to take care of the “Datapack questions”.

I also hope I can help you with this pull request. I put a lot of effort into it!

Here are the resolved issues with the tags: #131, #114, #106
I also fixed others: #130, #124, #106

Oh, and #66 should have been closed

### CODE REVIEW

**Comment by abidbmt** [comment]
This is great! How can i build this for fabric 1.20.1?

**Comment by MrRedstoneToGo** [comment]
I start a pull request

**Comment by BugInYourCode01** [comment]
1.20.1 only has one branch. If you add the changes in the pull request, it should work for both forge and fabric.

**Comment by MrRedstoneToGo** [comment]
Please not implemented yet, there is still a bit to do.

**Comment by BugInYourCode01** [comment]
Finally the pull request is completely ready for use. And in case anyone is wondering. I haven't changed the metal compaction recipes to tags, so you can't compress an ingot from another mod into a Create Deco storage block and then convert it into a Create Deco ingot.

**Comment by abidbmt** [comment]
> Finally the pull request is completely ready for use. And in case anyone is wondering. I haven't changed the metal compaction recipes to tags, so you can't compress an ingot from another mod into a Create Deco storage block and then convert it into a Create Deco ingot.

This does fix the issue with conflicting recipes tho right? Im talking about the zinc_ingot to zinc_sheet conflict between create: crafts and additions and create: deco

**Comment by BugInYourCode01** [comment]
Yes, you can now use Create Deco zinc sheets for the Crafts Additions' capacitor and Crafts Additions' zinc sheet for Create Deco recipes. One of the zinc sheets stays unobtainable but all other items from both mods with zinc sheets in the recipe become obtainable.

**Comment by drewcassidy** [comment]
So you're updated the generated json files but not the java files that generate them. how does that work?

**Comment by BugInYourCode01** [comment]
I did all this by hand (search, replace). Now I have learned that all the files are generated automatically (folder generated) and now I have to adapt the Java files for this. uff...

**Comment by BugInYourCode01** [comment]
I don't know how to implement this in code. I have the code in my head, but not the keywords / method names for it. In addition, it is practically impossible for me to have the code checked for its syntax or semantics (whether it does the right thing), so I have decided to close this pull request and put the features of this into an issue. The reposity will of course remain as a reference source as long as the issue still exists.

This is not the best solution, but at least the developers don't have to find out the cause/source anymore, they just have to automate my work.

**Pull request closed without merging**
