### PR TITLE
Make bars transparent to fans

### PR DESCRIPTION
**Pull request by drewcassidy**
Addresses #131

also removes superfluous walls tag on metal bars. walls automatically connect to any instance of IronBarsBlock
Screenshot 2024-02-22 at 7 47 39 PM

### CODE REVIEW

**Comment by BugInYourCode01** [comment]
Transparent bars tag: Maybe in the same order as the other items?
First all adesite alloy items, then brass, then iron...

**Comment by drewcassidy** [comment]
Im not sure what you mean by "order"

**Comment by BugInYourCode01** [comment]
You put all bars at the top of the file. Spread them, so andesite alloy bars are between the other andesite alloy items, zinc bars between the zinc items. It doesn't change anything in game but the code is more clean.

**Comment by drewcassidy** [comment]
Those are auto-generated files. They arguably shouldn't even be included in the GitHub repo. I have no control over what order things get added to them

**Comment by BugInYourCode01** [comment]
Why don't you change them manually? There aren't that many files. (2)

**Comment by drewcassidy** [comment]
Because the next time someone runs data generation they'll get overwritten. again, they shouldn't even be in the repo

**Comment by BugInYourCode01** [comment]
Ah, I should do that in my repo too, I was wondering how talrey made so many recipes.

**Pull request merged**
